name: aidoptics_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  #App specific
  path_provider: ^2.0.14
  image_picker: ^0.8.7+1
  file_picker: ^5.2.7
  http: ^1.1.2
  perfect_volume_control: ^1.0.5
  geolocator: ^7.1.0
  geocoding: ^2.1.0
  permission_handler: ^10.2.0
  camera: ^0.10.4
  image: ^4.0.15
  google_maps_flutter: ^2.5.0

  # ML
  google_mlkit_text_recognition: ^0.5.0
  google_mlkit_image_labeling: ^0.5.0
  flutter_face_api: ^5.2.3
  flutter_face_core: ^5.2.0
  flutter_tts: ^3.6.3

  # UI
  flutter_signin_button: ^2.0.0
  lottie: ^2.2.0


  #Basics
  flutter_native_splash: ^2.2.19
  

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
